version: "3.8"

services:
  fastapi:
    build: backend/
    ports:
      - 8000:8000
    networks:
      - deploy_network
    container_name: fastapi-backend
    volumes:
      - type: bind
        source: ./backend
        target: /backend

  streamlit:
    build: frontend/
    depends_on:
      - fastapi
    ports:
      - 8501:8501
    networks:
      - deploy_network
    container_name: frontend-streamlit
    volumes:
      - type: bind
        source: ./frontend
        target: /frontend

networks:
  deploy_network:
    driver: bridge
